name: PR build and run tests

on:
  push:
  pull_request:
    branches:
    - testing*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone
      run: |
          git fetch origin
          git checkout main
          git pull --unshallow
    - name : Install dependency packages
      run: |
          sudo apt install -y --no-install-recommends \
            git \
            cmake \
            clang-format
    - name : Format
      run: find . -regex '.*\.\(cpp\|hpp\|cxx\|cp\|cc\|cu\|c\|h\)' -exec clang-format -style=file -i {} \;
    - name : Configure
      run: cmake -DBUILD_TESTING=ON -S . -B build
    - name : Build
      run: cmake --build build -j$(nproc -all)
    - name : Run Tests
      run: |
          cd build
          ctest
