name: PR build and run tests

on:
pull_request:
branches:
  - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name : Install dependency packages 
      run: |
          sudo apt install -y --no-install-recommends \
            git \
            cmake \
            clang-format
    - name : Format
      run: find . -regex '.*\.\(cpp\|hpp\|cxx\|cp\|cc\|cu\|c\|h\)' -exec clang-format -style=file -i {} \;
    - name : Configure
      run: |
          cmake -DBUILD_TESTING=ON -S . -B build
    - name : Build
      run: |
          cmake --build build -j$(nproc -all)
    - name : Run Tests
      run: |
          cd build
          ctest
  -
